project_id = "ekfkrwueqwpqakpsrsjt"

[functions.widget-config]
verify_jwt = false

[functions.widget-analytics]
verify_jwt = false

[functions.add-sample-analytics]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-followup]
verify_jwt = false

[functions.live-chat-send]
verify_jwt = false

[functions.agendify-proxy]
verify_jwt = false

[functions.financial-webhook]
verify_jwt = false

[functions.financial-ai]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-setup]
verify_jwt = false

[functions.meta-webhook]
verify_jwt = false