project_id = "ekfkrwueqwpqakpsrsjt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ekfkrwueqwpqakpsrsjt.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[functions.openai-assistants]
verify_jwt = true

[functions.evolution-api]
verify_jwt = true

[functions.chat-api]
verify_jwt = true